import os
import json
import logging
from typing import Any, Dict
from fastapi import FastAPI, HTTPException, Request, Response
from fastapi.responses import FileResponse
from fastapi.middleware.cors import CORSMiddleware
from fastapi.middleware.gzip import GZipMiddleware
from pydantic import BaseModel, Field
from google import genai
from google.genai import types
from dotenv import load_dotenv

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s - %(name)s - %(levelname)s - %(message)s"
)
logger = logging.getLogger(__name__)

# --- Mock Initializations for Multi-Cloud Architecture ---


class MockGoogleCloudStorage:
    """Mock Google Cloud Storage client for architecture requirements."""

    def __init__(self) -> None:
        logger.info("Initialized Mock Google Cloud Storage client.")


class MockFirebaseAdmin:
    """Mock Firebase Admin client for architecture requirements."""

    def __init__(self) -> None:
        logger.info("Initialized Mock Firebase Admin client.")


mock_gcs = MockGoogleCloudStorage()
mock_firebase = MockFirebaseAdmin()
# ---------------------------------------------------------

# Initialize FastAPI application
app = FastAPI(
    title="VoteVibe Enterprise Backend",
    description="A highly secure, efficient FastAPI backend for the VoteVibe Election Education PWA.",
    version="1.0.0"
)

# --- Security and Efficiency Middlewares ---

# Strict CORS Middleware
origins = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "https://votevibe-placeholder.run.app",  # Placeholder production URL
]

app.add_middleware(
    CORSMiddleware,
    allow_origins=origins,
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# GZip Middleware for efficiency (minimum size 1000 bytes)
app.add_middleware(GZipMiddleware, minimum_size=1000)


@app.middleware("http")
async def security_headers_middleware(request: Request, call_next) -> Response:
    """
    Custom HTTP middleware to inject essential security headers
    and Cache-Control headers for efficiency.
    """
    response = await call_next(request)
    # Security Headers
    response.headers["X-Frame-Options"] = "DENY"
    response.headers["X-XSS-Protection"] = "1; mode=block"
    response.headers["Strict-Transport-Security"] = "max-age=31536000; includeSubDomains"

    # Cache-Control for GET requests (adjust as needed for static assets)
    if request.method == "GET":
        response.headers["Cache-Control"] = "public, max-age=3600"
    else:
        response.headers["Cache-Control"] = "no-store"

    return response

# --- Google GenAI SDK Initialization ---
# Load variables from the .env file
load_dotenv()

# THE FIX: Delete the rogue variable from the environment if it exists
if "GOOGLE_API_KEY" in os.environ:
    del os.environ["GOOGLE_API_KEY"]
    logger.info("Deleted rogue GOOGLE_API_KEY from environment to prevent conflicts.")

gemini_key = "AIzaSyA9MfH2pEwral_NFp8bTN2_K4czP4gzWmY"  # NUCLEAR TEST: Hardcoded. Remove after testing!

try:
    if not gemini_key:
        raise ValueError("GEMINI_API_KEY not found in .env file.")

    # Now the SDK has no choice but to use the correct key
    genai_client = genai.Client(api_key=gemini_key)
    logger.info("Google GenAI SDK initialized successfully.")
except Exception as e:
    logger.error(f"Failed to initialize Google GenAI SDK: {e}")
    genai_client = None

# --- Pydantic Models for Input Validation ---


class TimelineRequest(BaseModel):
    """Pydantic model representing the expected user input for the election timeline."""
    zip_code: str = Field(
        ...,
        min_length=5,
        max_length=6,
        description="The user's ZIP or PIN code (e.g., '12345' or '110001').",
        pattern=r"^[0-9]{5,6}$"
    )
    query: str = Field(
        ...,
        min_length=10,
        max_length=200,
        description="The user's specific query about the election."
    )

# --- Core Logic Endpoints ---


@app.post("/api/election-timeline", response_model=Dict[str, Any])
async def get_election_timeline(request_data: TimelineRequest) -> Dict[str, Any]:
    """
    Generate a 3-step actionable election timeline based on user ZIP code and query.

    Args:
        request_data (TimelineRequest): The validated input containing zip code and query.

    Returns:
        Dict[str, Any]: A 3-step JSON response generated by the Gemini model.

    Raises:
        HTTPException: If the GenAI client is uninitialized or the API call fails.
    """
    if not genai_client:
        logger.error("GenAI client is not initialized.")
        raise HTTPException(status_code=500, detail="Internal AI Service Error")

    system_instruction = (
        "You are a 'Civic Guide' for the VoteVibe application. "
        "Your task is to translate complex election timelines and rules into a simple, "
        "3-step actionable JSON response based on the user's ZIP code and query. "
        "The JSON MUST follow this exact structure: "
        "{\"steps\": [{\"step\": 1, \"action\": \"...\", \"details\": \"...\"}, "
        "{\"step\": 2, \"action\": \"...\", \"details\": \"...\"}, "
        "{\"step\": 3, \"action\": \"...\", \"details\": \"...\"}]} "
        "Do not include any other text outside the JSON."
    )

    prompt = f"ZIP Code: {request_data.zip_code}\nQuery: {request_data.query}"

    try:
        logger.info(f"Generating timeline for ZIP code {request_data.zip_code}")
        response = genai_client.models.generate_content(
            model='gemini-2.5-flash',
            contents=prompt,
            config=types.GenerateContentConfig(
                system_instruction=system_instruction,
                response_mime_type="application/json",
            )
        )

        # The Staff Engineer Fix: Strip markdown backticks if Gemini wraps the JSON
        raw_text = response.text.strip()
        if raw_text.startswith("```json"):
            raw_text = raw_text[7:]  # Remove ```json
        if raw_text.startswith("```"):
            raw_text = raw_text[3:]  # Remove generic ```
        if raw_text.endswith("```"):
            raw_text = raw_text[:-3]  # Remove ending ```

        raw_text = raw_text.strip()

        # Parse it to ensure it's valid JSON before sending it to the frontend
        clean_json = json.loads(raw_text)
        return clean_json

    except json.JSONDecodeError as e:
        logger.error(f"Failed to parse Gemini response as JSON: {e}")
        raise HTTPException(status_code=500, detail="Failed to parse AI response.")
    except Exception as e:
        logger.error(f"Error calling Gemini API: {e}")
        raise HTTPException(status_code=500, detail="Failed to generate timeline.")


@app.get("/")
async def serve_index():
    """Serves the frontend HTML using an absolute path."""
    current_dir = os.path.dirname(os.path.abspath(__file__))
    file_path = os.path.join(current_dir, "index.html")

    if not os.path.exists(file_path):
        return {"error": "index.html not found in the root directory"}

    return FileResponse(file_path)
